### ISSUE TITLE
How to get data from reference field firestore using React Native

### ISSUE THREAD

**Issue by bl4ckck** [WildanZq/PetShop-ReactNative#5]
I want to show the data reference 'boards' from 'penjualan'. When I try to show data value from reference (like title) it show nothing. But when I show the data (not reference type) from 'penjualan' it show the result.

**This is my database structure.**

Boards
<img src="https://imgbbb.com/images/2019/03/17/boards.png">

Penjualan
<img src="https://imgbbb.com/images/2019/03/17/penjualan.png">

**My codes.**
`

    constructor() {
      super();
      this.state = {
        penjualan: []
      };  
      this.unsubscribe = null;
      this.dataNya = firebase.firestore().collection("penjualan");
    }

    onCollectionUpdate = querySnapshot => {
      const penjualan = [];

      querySnapshot.forEach(doc => {
        const { total, barang } = doc.data();

        barang.get().then(res => {
          const {title} = res.data();

          penjualan.push({title});
        })
        .catch(err => console.error(err));

        penjualan.push({
          total
        });
      });

      this.setState({
        penjualan
      });
    };

    componentDidMount() {
      this._showData();
      this.unsubscribe = this.dataNya.onSnapshot(this.onCollectionUpdate);
    }

    render() {
    return (
        <View style={[styles.container]}>
          {this.state.penjualan.map((item, i) => ( <View key={i}><Text>{item.title}</Text></View>))}
        </View>
    )
    }

`

**Comment by dion-ricky** [comment]
kagak paham vin mungkin @WildanZq bisa

**Comment by bl4ckck** [comment]
Solved
